### ISSUE TITLE
unique track_id guaranteed?

### ISSUE THREAD

**Issue by dewyeon** [maxmarkov/track_and_count#6]
Hello.
First of all, thank you for your great work. 

I have this one little question. Is unique track_id guaranteed? I made an inference of a video using the `track_yolov5_pose.py` and got the same track_id for 2 different people. (two different people from each different frame, one from frame about #80, another from frame about #640)

Is this because the unique track_id is not guaranteed? or is it because the detection/tracking failed?

**Comment by maxmarkov** [comment]
Hi @dewyeon,

Thank you for your interest in my work. 

ID switching is possible in all trackers (including SORT and DeepSORT used in this work). Usually it occurs in difficult situations such as a crowd (many similar objects are concentrated close to each other). But there may be many different reasons.

You can look carefully at your inference video and identify the moment when the switch occurs to understand it better. Most likely, person 1 walks all over the place, then passes next to person 2 when the switch occurs.`track_yolov5_pose.py` uses the DeepSORT algorithm which tracks the object ('person' only) based on appearance feature vectors coming from a separate network trained to distinguish different people. Feature vectors are compared based on the cosine metric in every frame between all bounding boxes found in this frame (with person class only). For instance, it could be that the bounding box with person 1 has not been detected, while person 2 with similar appearance feature was detected nearby. So the algorithm just got confused between them.

**Comment by dewyeon** [comment]
Thank you for the detailed explanation.
